import localFont from "next/font/local";
import {PT_Sans, Pattaya} from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const pt_sans = PT_Sans({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-pt-sans',
	adjustFontFallback: false,
	weight: ["400", "700"]
})

const pattaya = Pattaya({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-pattaya',
	weight: ["400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pt_sans.variable} ${pattaya.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
